---
name: Deployment
#on:
#  push:
#    branches:
#      - master
on: push
jobs:
#  phpstan:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: php-actions/composer@v6
#        with:
#          working_dir: app/
#      - name: PHPStan static analysis
#        run: "./app/vendor/bin/phpstan analyse -c ./app/phpstan.neon"

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: lorddistrict/vtiger/vtiger
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            cd vtiger-docker
            docker compose pull
            docker compose up -d
